apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: installargo
spec:
  generators:
  - list:
      elements:
        - appName: customer-argocd
          namespace: argocd-customer 
  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default 
      source:
        repoURL: https://github.com/ghebu/argocd-poc.git 
        targetRevision: HEAD
        path: "argocd-helm/charts/argo-cd"
        helm:
          # Release name override (defaults to application name)
          releaseName: "{{appName}}"
          valueFiles:
          - "values.yaml"
      destination:
        # Default base cluster
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

